version: "3.8"
services:
  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - service_users
      - service_orders
    environment:
      - USERS_URL=http://service_users:8001/v1
      - ORDERS_URL=http://service_orders:8002/v1
      - JWT_SECRET=super-secret-change-this
      - OTEL_COLLECTOR_URL=http://otel-collector:4318
    networks:
      - appnet

  service_users:
    build:
      context: ./service_users
    ports:
      - "8001:8001"
    volumes:
      - users_data:/data
    environment:
      - JWT_SECRET=super-secret-change-this
      - OTEL_COLLECTOR_URL=http://otel-collector:4318
      - OTEL_COLLECTOR_URL=http://otel-collector:4318
    networks:
      - appnet

  service_orders:
    build:
      context: ./service_orders
    ports:
      - "8002:8002"
    volumes:
      - orders_data:/data
    environment:
      - JWT_SECRET=super-secret-change-this
      - OTEL_COLLECTOR_URL=http://otel-collector:4318
      - OTEL_COLLECTOR_URL=http://otel-collector:4318
    networks:
      - appnet

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.79.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    networks:
      - appnet

volumes:
  users_data:
  orders_data:

networks:
  appnet:
